-- ============================================================================
-- GOM | SME — Schema Supabase (Fase 1: fundação)
-- ----------------------------------------------------------------------------
-- Como usar:
--   1. Crie o projeto no Supabase.
--   2. Abra o SQL Editor e cole este arquivo inteiro.
--   3. Rode (Run). É seguro rodar mais de uma vez (idempotente).
--
-- O que este arquivo cria:
--   - Tabelas de apoio (status_chamado, status_obra)
--   - Cadastros (escolas, equipes)
--   - Núcleo operacional (solicitacoes, anexos, historico_equipes, log_acoes)
--   - Obras
--   - Configurações (chave/valor)
--   - Índices e gatilhos de updated_at
--   - RLS ligado com política TEMPORÁRIA permissiva (equivale ao modo ABERTO de
--     hoje). A Fase 2 (auth + perfis) troca essas políticas antes de ir ao ar.
--   - Seeds: status (com cores), status de obras e as configurações padrão.
--
-- Dados das planilhas NÃO entram aqui — a migração é uma etapa posterior.
-- ============================================================================

-- ─── Função utilitária: atualiza updated_at automaticamente ─────────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ============================================================================
-- TABELAS DE APOIO (lookups)
-- ============================================================================

-- Status dos chamados: nome canônico + cor + ordem de exibição.
-- Substitui GOM_CONFIG.STATUS.TODOS e GOM_CONFIG.CORES_STATUS.
create table if not exists public.status_chamado (
  codigo text primary key,
  cor    text not null default '#002b5e',
  ordem  int  not null default 0,
  ativo  boolean not null default true
);

-- Status das obras. Substitui GOM_CONFIG.STATUS_OBRAS.
create table if not exists public.status_obra (
  codigo text primary key,
  ordem  int  not null default 0,
  ativo  boolean not null default true
);


-- ============================================================================
-- CADASTROS
-- ============================================================================

-- Unidades escolares (aba "Escolas").
create table if not exists public.escolas (
  id         bigint generated by default as identity primary key,
  nome       text not null unique,            -- Unidade Escolar
  tipo       text,                            -- CEI / EMEI / EMEF / ...
  endereco   text,
  telefone   text,
  email      text,
  ativo      boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Equipes (abas "Equipes" e "Equipes Empresa" unificadas via coluna tipo).
create table if not exists public.equipes (
  id         bigint generated by default as identity primary key,
  nome       text not null,                   -- Nome da Equipe
  tipo       text not null default 'secretaria'
             check (tipo in ('secretaria','empresa')),
  ativo      boolean not null default true,
  created_at timestamptz not null default now(),
  unique (nome, tipo)
);


-- ============================================================================
-- NÚCLEO OPERACIONAL
-- ============================================================================

-- Chamados / solicitações (abas "Solicitações" + "Solicitações concluídas").
-- "Concluído" é apenas um valor de situacao, não uma tabela separada.
create table if not exists public.solicitacoes (
  id                          bigint generated by default as identity primary key,

  -- Identificação / origem
  data_abertura               timestamptz not null default now(),   -- Data
  origem                      text,                                 -- Origem (ex.: "Solar 2025 -230786")
  escola_id                   bigint references public.escolas(id),  -- Unidade Escolar
  tipo                        text,                                 -- Tipo (CEI/EMEI/EMEF...)
  detalhamento                text,                                 -- Detalhamento
  classificacao               text,                                 -- Classificação (legado)

  -- Fluxo / status
  situacao                    text not null default 'Em análise'
                              references public.status_chamado(codigo),
  responsavel                 text,                                 -- Responsável
  resolvido                   boolean,                              -- Resolvido?

  -- Empresa / OS / orçamento
  numero_os                   text,                                 -- Nº da OS
  valor_orcamento             numeric(12,2),                        -- Valor orçamento
  equipe_responsavel          text,                                 -- Equipe responsável

  -- Observações
  observacoes                 text,                                 -- Observações
  observacao_antiga           text,                                 -- Observação antiga (legado)
  campo_auxiliar              text,                                 -- Campo auxiliar (legado/diversos)

  -- Datas de fluxo
  data_equipe                 date,        -- Data da equipe (dia da equipe do dia atual)
  data_agendamento_visita     date,        -- Data agendamento visita
  data_prevista_conclusao     date,        -- Data prevista conclusão
  data_conclusao              date,        -- Data conclusão
  data_conclusao_os           date,        -- Data conclusão OS

  data_hora_encaminhamento    timestamptz, -- Data/hora encaminhamento
  data_hora_entrada_fila      timestamptz, -- Data/hora entrada em atendimento (entrada na fila)
  data_hora_ultima_acao       timestamptz, -- Data/hora última ação

  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now()
);

-- Anexos (Storage). Substitui as 3 colunas de texto com links do Drive.
create table if not exists public.anexos (
  id             bigint generated by default as identity primary key,
  solicitacao_id bigint not null references public.solicitacoes(id) on delete cascade,
  categoria      text not null check (categoria in ('solicitacao','orcamento','servico')),
  nome           text,                       -- nome original do arquivo
  storage_path   text not null,              -- caminho no bucket do Storage
  mime_type      text,
  tamanho_bytes  bigint,
  created_at     timestamptz not null default now()
);

-- Histórico de equipes / execução diária (aba "Histórico de Equipes").
-- registrado_em guarda o instante EXATO do registro (resolve de vez a
-- "armadilha do UTC" do Apps Script: timestamptz + now() já grava certo).
create table if not exists public.historico_equipes (
  id                       bigint generated by default as identity primary key,
  registrado_em            timestamptz not null default now(),     -- Data/hora registro
  data_atendimento         date,                                   -- Data atendimento (dia escolhido)
  solicitacao_id           bigint references public.solicitacoes(id),
  status                   text references public.status_chamado(codigo),
  numero_os                text,                                   -- Nº da OS
  equipe                   text,                                   -- Equipe
  observacoes_dia          text,                                   -- Observações do dia
  data_prevista_conclusao  date,
  data_conclusao           date,
  usuario                  text,                                   -- e-mail de quem registrou
  tipo_registro            text                                    -- ex.: equipe_dia / orcamento / os
);

-- Log de ações (auditoria) — aba "Log de ações".
create table if not exists public.log_acoes (
  id              bigint generated by default as identity primary key,
  registrado_em   timestamptz not null default now(),  -- Data/hora
  usuario         text,                                -- Usuário
  solicitacao_id  bigint references public.solicitacoes(id),
  acao            text,                                -- Ação
  status_anterior text,                                -- Status anterior
  status_novo     text,                                -- Status novo
  observacao      text,                                -- Observação
  valor_orcamento numeric(12,2),                       -- Valor orçamento
  equipe          text,                                -- Equipe
  origem          text                                 -- Origem
);


-- ============================================================================
-- OBRAS (aba "Ampliações e Construções")
-- ============================================================================
create table if not exists public.obras (
  id                    bigint generated by default as identity primary key,
  escola_id             bigint references public.escolas(id),   -- Unidade Escolar
  tipo_obra             text,                                   -- Tipo de obra
  descricao             text,                                   -- Descrição
  status                text not null default 'Aguardando'
                        references public.status_obra(codigo),  -- Status
  prioridade            text check (prioridade in ('P0','P1','P2','P3')),
  responsavel           text,                                   -- Responsável
  responsavel2          text,                                   -- Responsável 2
  prazo_previsto        date,                                   -- Prazo previsto
  valor_estimado        numeric(14,2),                          -- Valor estimado
  observacoes           text,                                   -- Observações
  data_hora_ultima_acao timestamptz,                            -- Data/hora última ação
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);


-- ============================================================================
-- CONFIGURAÇÕES (aba "Configurações do Sistema") — chave/valor
-- ============================================================================
create table if not exists public.configuracoes (
  chave      text primary key,
  valor      text,
  grupo      text,
  descricao  text,
  ativo      boolean not null default true,
  updated_at timestamptz not null default now()
);


-- ============================================================================
-- ÍNDICES
-- ============================================================================
create index if not exists idx_solicitacoes_situacao  on public.solicitacoes (situacao);
create index if not exists idx_solicitacoes_escola    on public.solicitacoes (escola_id);
create index if not exists idx_solicitacoes_abertura  on public.solicitacoes (data_abertura);
create index if not exists idx_anexos_solicitacao     on public.anexos (solicitacao_id);
create index if not exists idx_hist_solicitacao       on public.historico_equipes (solicitacao_id);
create index if not exists idx_hist_data              on public.historico_equipes (data_atendimento);
create index if not exists idx_log_solicitacao        on public.log_acoes (solicitacao_id);
create index if not exists idx_obras_status           on public.obras (status);
create index if not exists idx_obras_escola           on public.obras (escola_id);


-- ============================================================================
-- GATILHOS updated_at
-- ============================================================================
drop trigger if exists trg_escolas_updated     on public.escolas;
create trigger trg_escolas_updated     before update on public.escolas
  for each row execute function public.set_updated_at();

drop trigger if exists trg_solicit_updated     on public.solicitacoes;
create trigger trg_solicit_updated     before update on public.solicitacoes
  for each row execute function public.set_updated_at();

drop trigger if exists trg_obras_updated       on public.obras;
create trigger trg_obras_updated       before update on public.obras
  for each row execute function public.set_updated_at();

drop trigger if exists trg_config_updated      on public.configuracoes;
create trigger trg_config_updated      before update on public.configuracoes
  for each row execute function public.set_updated_at();


-- ============================================================================
-- GRANTS — TEMPORÁRIO PARA HOMOLOGAÇÃO
-- ----------------------------------------------------------------------------
-- A política RLS permissiva precisa vir acompanhada dos GRANTS abaixo para que
-- a role anon consiga acessar a API REST sem erro 401/403 durante a Fase 1.
-- Antes da produção, substituir por autenticação + RLS restritiva por perfil.
-- ============================================================================
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ============================================================================
-- RLS — TEMPORÁRIO (equivale ao modo ABERTO atual)
-- ----------------------------------------------------------------------------
-- ATENÇÃO: estas políticas liberam acesso total (anon). É só para homologação,
-- exatamente como o sistema roda hoje (PERMISSOES_MODO = ABERTO).
-- A Fase 2 (auth Google + perfis) SUBSTITUI tudo isto ANTES de ir ao ar.
-- ============================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'status_chamado','status_obra','escolas','equipes','solicitacoes',
    'anexos','historico_equipes','log_acoes','obras','configuracoes'
  ]
  loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists tmp_aberto_all on public.%I;', t);
    execute format(
      'create policy tmp_aberto_all on public.%I for all to anon, authenticated using (true) with check (true);',
      t
    );
  end loop;
end $$;


-- ============================================================================
-- SEEDS — status dos chamados (nome canônico + cor + ordem)
-- ============================================================================
insert into public.status_chamado (codigo, cor, ordem) values
  ('Em análise',                                          '#FFD300', 10),
  ('Solicitado Orçamento',                                '#f59e0b', 20),
  ('Orçamento Realizado',                                 '#fb923c', 30),
  ('Aguardando visita',                                   '#14b8a6', 40),
  ('Em atendimento',                                      '#00e5ff', 50),
  ('Atendimento Emergencial',                             '#ec4899', 60),
  ('OS emitida',                                          '#22d3ee', 70),
  ('Serviço Realizado',                                   '#10b981', 80),
  ('Garantia de Obra',                                    '#d97706', 90),
  ('Visita Técnica',                                      '#14b8a6', 100),
  ('Devolvido para a escola',                             '#64748b', 110),
  ('Concluído',                                           '#39FF14', 120),
  ('Encaminhado para outra gerência ou Unidade escolar.', '#6366f1', 130),
  ('A cargo da unidade escolar',                          '#84cc16', 140),
  ('Duplicado',                                           '#475569', 150)
on conflict (codigo) do update set cor = excluded.cor, ordem = excluded.ordem;


-- ============================================================================
-- SEEDS — status de obras
-- ============================================================================
insert into public.status_obra (codigo, ordem) values
  ('Aguardando',   10),
  ('Em projeto',   20),
  ('Em licitação', 30),
  ('Em execução',  40),
  ('Suspensa',     50),
  ('Concluída',    60),
  ('Arquivada',    70)
on conflict (codigo) do update set ordem = excluded.ordem;


-- ============================================================================
-- SEEDS — configurações padrão (GOM_CONFIG.CONFIGURACOES_PADRAO)
-- ============================================================================
insert into public.configuracoes (chave, valor, grupo, descricao, ativo) values
  ('PERMISSOES_MODO','ABERTO','Permissões','ABERTO mantém acesso total para configuração/homologação. RESTRITO aplica perfis por e-mail.',true),
  ('EMAILS_ADMIN_GOM','','Permissões','E-mails administradores com acesso total.',true),
  ('EMAILS_GOM_OPERACIONAL','','Permissões','E-mails da equipe GOM operacional. Acesso às telas de operação, sem Configurações.',true),
  ('EMAILS_EMPRESA_ADICIONAIS','','Permissões','E-mails adicionais da empresa, além de EMAIL_EMPRESA.',true),
  ('EMAILS_CAMPO','','Permissões','E-mails de usuários de campo. Acesso à tela Campo e Acompanhar.',true),
  ('EMAILS_CONFERENTE','','Permissões','E-mails de conferentes. Leitura de dashboard, obras, memorial e relatórios.',true),
  ('PERFIL_SEM_LOGIN','PUBLICO','Permissões','Perfil usado quando não há e-mail identificado. Sugestão: PUBLICO.',true),
  ('EMAIL_EMPRESA','','Empresa','E-mail da empresa que receberá cobranças e avisos operacionais.',true),
  ('NOME_EMPRESA','','Empresa','Nome da empresa responsável pelos atendimentos.',true),
  ('EMAIL_RESPONSAVEL_GOM','','Empresa','E-mail interno da GOM para cópias, avisos e alertas.',true),
  ('HORARIO_LIMITE_CAMPO','11:00','Empresa','Horário limite para a empresa registrar as equipes do dia.',true),
  ('SLA_ANALISE_DIAS','3','Prazos/SLA','Prazo máximo desejado para chamados novos/em análise sem movimentação.',true),
  ('SLA_VISITA_DIAS','3','Prazos/SLA','Prazo máximo desejado para chamados aguardando visita.',true),
  ('SLA_ORCAMENTO_DIAS','5','Prazos/SLA','Prazo máximo desejado para retorno de orçamento solicitado.',true),
  ('SLA_APROVACAO_DIAS','2','Prazos/SLA','Prazo máximo desejado para análise de orçamento realizado.',true),
  ('SLA_OS_DIAS','7','Prazos/SLA','Prazo de referência para execução de OS emitida.',true),
  ('SLA_FINALIZACAO_DIAS','2','Prazos/SLA','Prazo para validação interna após serviço realizado.',true),
  ('ALERTA_COBRANCA_CAMPO_ATIVO','SIM','Alertas','Ativa cobrança automática quando não houver preenchimento diário da empresa.',true),
  ('ALERTA_EMAIL_EMPRESA_ATIVO','SIM','Alertas','Permite envio de e-mails de alerta para a empresa.',true),
  ('ALERTA_OS_SEM_NUMERO_ATIVO','SIM','Alertas','Destaca OS emitida sem numeração preenchida.',true),
  ('ALERTA_ORCAMENTO_SEM_RETORNO_ATIVO','SIM','Alertas','Destaca orçamentos solicitados sem retorno dentro do prazo.',true),
  ('ALERTA_ANALISE_PARADA_ATIVO','SIM','Alertas','Destaca chamados em análise sem interação acima do SLA.',true),
  ('ALERTA_VISITA_ATRASADA_ATIVO','SIM','Alertas','Destaca chamados aguardando visita acima do prazo configurado.',true),
  ('ALERTA_APROVACAO_PARADA_ATIVO','SIM','Alertas','Destaca orçamentos realizados aguardando decisão acima do SLA.',true),
  ('ALERTA_PREVISAO_VENCIDA_ATIVO','SIM','Alertas','Destaca OS com data prevista de conclusão vencida.',true),
  ('ALERTA_OS_SEM_PREVISAO_ATIVO','SIM','Alertas','Destaca OS em campo sem data prevista de conclusão.',true),
  ('ALERTA_SERVICO_SEM_FINALIZACAO_ATIVO','SIM','Alertas','Destaca serviço realizado ainda não finalizado no prazo.',true),
  ('NOME_SISTEMA','Gestão GOM','Sistema','Nome exibido nos e-mails e telas públicas.',true),
  ('SETOR_RESPONSAVEL','GOM | SME','Sistema','Identificação institucional do setor responsável.',true),
  ('TIMEZONE','America/Sao_Paulo','Sistema','Fuso horário utilizado nos registros e alertas.',true),
  ('LIMITE_ANEXOS','5','Anexos','Quantidade máxima de arquivos por envio.',true),
  ('TAMANHO_MAX_MB','8','Anexos','Tamanho máximo de cada anexo em MB.',true),
  ('STATUS_PADRAO_NOVO_CHAMADO','Em análise','Status','Status inicial padrão para novos chamados.',true),
  ('STATUS_DEVOLVIDO_MEMORIAL','Devolvido para a escola','Status','Status usado quando a solicitação é devolvida para a unidade e encerrada no Memorial.',true)
on conflict (chave) do nothing;

-- ============================================================================
-- FIM — Fase 1
-- ============================================================================

-- ============================================================================
-- COMPLEMENTO: GERENCIAL DE EQUIPES / INTEGRANTES
-- ============================================================================
create table if not exists public.equipe_membros (
  id         bigint generated by default as identity primary key,
  equipe_id  bigint not null references public.equipes(id) on delete cascade,
  nome       text not null,
  funcao     text,
  telefone   text,
  email      text,
  ativo      boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (equipe_id, nome)
);

create index if not exists idx_equipe_membros_equipe on public.equipe_membros (equipe_id);
create index if not exists idx_equipe_membros_ativo  on public.equipe_membros (ativo);

grant select, insert, update, delete on public.equipe_membros to anon, authenticated;

alter table public.equipe_membros enable row level security;
drop policy if exists tmp_aberto_all on public.equipe_membros;
create policy tmp_aberto_all on public.equipe_membros
for all to anon, authenticated
using (true)
with check (true);
