-- ============================================================================
-- GOM | Gerencial de Equipes
-- Cria o vínculo entre equipes e integrantes.
-- Rode este arquivo uma vez no Supabase SQL Editor.
-- ============================================================================

create table if not exists public.equipe_membros (
  id         bigint generated by default as identity primary key,
  equipe_id  bigint not null references public.equipes(id) on delete cascade,
  nome       text not null,
  funcao     text,
  telefone   text,
  email      text,
  ativo      boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (equipe_id, nome)
);

create index if not exists idx_equipe_membros_equipe on public.equipe_membros (equipe_id);
create index if not exists idx_equipe_membros_ativo  on public.equipe_membros (ativo);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.equipe_membros to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter table public.equipe_membros enable row level security;
drop policy if exists tmp_aberto_all on public.equipe_membros;
create policy tmp_aberto_all on public.equipe_membros
for all to anon, authenticated
using (true)
with check (true);
